### ISSUE TITLE
錯誤

### ISSUE THREAD

**Issue by rex920327** [Lin-jun-xiang/chatgpt-line-bot#2]
Exception in callback Task.task_wakeup(<Future finished result=None>)
handle: <Handle Task.task_wakeup(<Future finished result=None>)>
Traceback (most recent call last):
  File "/nix/store/1gc9wvzsy15pclrqfspii166p52lmh5i-python3-3.10.13/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-1' coro=<Server.serve() running at /home/runner/chatgpt-line-bot2/.pythonlibs/lib/python3.10/site-packages/uvicorn/server.py:81> wait_for=<Future finished result=None> cb=[_run_until_complete_cb() at /nix/store/1gc9wvzsy15pclrqfspii166p52lmh5i-python3-3.10.13/lib/python3.10/asyncio/base_events.py:184]> while another task <Task pending name='Task-6' coro=<RequestResponseCycle.run_asgi() running at /home/runner/chatgpt-line-bot2/.pythonlibs/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py:408> cb=[set.discard()]> is being executed.
RetryProvider failed:
ChatgptAi: ClientResponseError: 404, message='Not Found', url=URL('https://chatgate.ai/wp-json/mwai-ui/v1/chats/submit')
GeekGpt: HTTPError: 526 Server Error:  for url: https://ai.fakeopen.com/v1/chat/completions
ChatAnywhere: ClientConnectorError: Cannot connect to host chatanywhere.cn:443 ssl:default [No address associated with hostname]
GptGo: ClientResponseError: 403, message='Forbidden', url=URL('https://gptgo.ai/get_token.php')
Bing: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1199.4')
You: RequestsError: HTTP Error 403: 
Chatgpt4Online: ClientResponseError: 403, message='Forbidden', url=URL('https://chatgpt4online.org/')

**Comment by Lin-jun-xiang** [comment]
This error was cause from `gpt4free`, u should keep update `g4f` package avoid the problem.
